language: cpp

os:
  - linux

dist: trusty

sudo: required

compiler:
  - gcc

env:
  - BUILD_TYPE=Release

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake make gcc-5
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

script:
  - mkdir build
  - cd build
  # - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=g++-5 ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j
