language: cpp
dist: precise
sudo: required
compiler:
  - gcc-5
os:
  - linux
addons:
  - cmake
  - make
  apt:
    packages:
      - g++-5
    sources:
      - ubuntu-toolchain-r-test
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - cmake -DCMAKE_CXX_COMPILER=g++-5
  - make
  - ./examples/simple_function/simple_function
  - ./examples/pinhole/pinhole