language: cpp
dist: precise
compiler:
  - gcc-5
os:
  - linux
addons:
  - cmake
  - make
install:
  - sudo apt install g++-5
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - cmake -DCMAKE_CXX_COMPILER=g++-5
  - make
  - ./examples/simple_function/simple_function
  - ./examples/pinhole/pinhole